### ISSUE TITLE
fix: template selection in the prompt fails with cookiecutter==2.6.0.

### ISSUE THREAD

**Issue by ycexiao** [scikit-package/scikit-package-manuscript#21]
### Problem

Following the level 4 tutorial, we get `cookiecutter=2.6.0`
```
conda config --add channels conda-forge
conda create -n skpkg-env scikit-package pre-commit
pip show cookiecutter
```
Using `cookiecutter=2.6.0` to run `cookiecutter scikit-package-manuscript`, we get

```
AttributeError: 'NoneType' object has no attribute 'group'. 
```

Changing the `cookiecutter` to an older version like `1.7.3` can fix this. 
### Proposed solution

(1) Keep `cookiecutter=1.7.3` as default.

And the format of `~/.skpkgrc` needs to change from `json` to `yaml` in `cookiecutter=1.7.3`. 

(2) Use `cookiecutter=2.6.0` as default and rewrite the template selection feature.

I think we can temporarily use solution (1) in this repo to close  #12, and get solution (2) done in the future.

**Comment by ycexiao** [comment]
@sbillinge, please check this.

**Comment by ycexiao** [comment]
And I am not sure it is the reason, but the `package create manuscript` command fails on my local machine. If it is the case, we may need to remove `manuscript` from our `scikit-package` release for now.

**Comment by ycexiao** [comment]
A workable `~/.skpkgrc` example in `cookiecutter=1.7.3` :
```yaml
default_context:
    project_name: "my-package"
    github_username_or_orgname: "billingegroup"
    github_repo_name: "{{ cookiecutter.project_name|replace(' ', '-')|lower }}"
    conda_pypi_package_dist_name: "{{ cookiecutter.project_name|replace(' ', '-')|lower }}"
    package_dir_name: "{{ cookiecutter.project_name|replace(' ', '_')|replace('-', '_')|lower }}"
    contributor": "Sangjoon Lee, Simon Billinge"

```
